### ISSUE TITLE
Installation of libfolia

### ISSUE THREAD

**Issue by peterverhaar** [LanguageMachines/libfolia#12]
When I try to install libfolia, I consistently receive the following error message:
 
grep: /usr/lib/libiconv.la: No such file or directory
sed: /usr/lib/libiconv.la: No such file or directory
libtool:   error: '/usr/lib/libiconv.la' is not a valid libtool archive
 
I am working on a Mac OS Sierra environment, version 10.12.3. The folder that is mentioned does not contain a libiconv.la file. There is a libiconv.dylib file, however. I have tried to install libiconv using homebrew on my machine, but this did not create a libiconv.la file either.
 
Does anybody have an idea of what may be causing this problem, and of how I may solve this issue? I have attached the config.log file. 

Any help would be greatly appreciated!

[config-log.txt](https://github.com/LanguageMachines/libfolia/files/864479/config-log.txt)

**Comment by proycon** [comment]
It seems the problem is unrelated to libfolia as such, but there is something wrong with some of these basic unix utilities on your mac installation. ``grep``, ``sed`` and ``libtool`` may all depend on iconv, and something seems to have gotten messed up on the system. I assume if you just run ``grep`` or ``sed`` in a terminal, it immediately fails with the same error?

On mac I more often see things that are installed through homebrew might conflict with things provided by apple. It's not as neatly organised as on linux distributions. Perhaps a homebrew version of iconv may even stand in the way here.

**Comment by kosloot** [comment]
Maybe it helps to install 'grep' 'sed' and 'libtool' using HomeBrew too?
</wild guess>

**Comment by kosloot** [comment]
closing because of lack of feedback
