### ISSUE TITLE
br should inherit from AbstractMarkupElement as well

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/libfolia#14]
br is both structure annotation and markup annotation, but right now folialint fails on the xlink:href attribute:  

unsupported attribute: href='http://resources.huygens.knaw.nl/retroapp/service_declercq/13/images/0180.tiff' for node with tag 'br'

**Comment by kosloot** [comment]
Multiple inheritage is impossible, because both AbstractTextMarkup and AbstractStructureElement have a static PROPS memer as well as a number of the same functions.
Changing this is VERY difficult, and will lead to convoluted code.
Just setting AbstractactTextMarkup.PROPS.XLINK to true is far more easy.
